server:
  port: 7003
spring:
  application:
    name: changgou-file
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
dfs:
  connect-timeout: 60
  network-timeout: 60
  charset: UTF-8
  tracker-http-port: 8080
  tracker-server:
    - 192.168.10.108:22122