server:
  port: 7002
spring:
  application:
    name: goods-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/changgou_goods?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    # 配置sql日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.changgou.goods.entity
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.10.108:7001/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
